apiVersion: v2
name: helm-chart-test
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.22.0"
maintainers:
  - name: jamesmiller
    email: james1miller93@gmail.com
